name: Vite CI/CD Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 使用别人封装好的的action，用于clone该仓库的源码到工作流中
      - name: Checkout
        uses: actions/checkout@v3
      # 在工作流中安装node环境（必需，这样才能在后续工作流程中运行 npm install 等指令，否则会报错）
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 指定node版本
      # 打包代码生成环境
      - name: Build
        run: |
          npm install # 安装依赖
          npm run build # 打包前端代码到生产环境
      # 部署
      - name: Deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.HOST_USER }} # 服务器用户名
          pass: ${{ secrets.HOST_PASS }} # 服务器密码
          connect_timeout: 30s
          local: './dist/*' # 源路径（工作流）
          remote: /www/wwwroot/cicd.zeroojs.com # 目标路径（服务器）